### ISSUE TITLE
clang-omp not finding <stdio.h> / <omp.h>

### ISSUE THREAD

**Issue by jamesblackburn** [Homebrew/legacy-homebrew#40391]
Hi

I've installed clang-omp but there seem to be issues with it picking up built-in headers.

It is installed locally, but running tests doesn't work:

```
(arctic)JB-MacBook:arctic james$ brew install clang-omp
Warning: clang-omp-2015-04-01 already installed
(arctic)JB-MacBook:arctic james$ brew test clang-omp
Testing clang-omp
==> /usr/local/Cellar/clang-omp/2015-04-01/bin/clang-omp -liomp5 -fopenmp test.c -o test

test.c:3:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.
Error: clang-omp: failed
Failed executing: /usr/local/Cellar/clang-omp/2015-04-01/bin/clang-omp -liomp5 -fopenmp test.c -o test
/usr/local/Library/Homebrew/formula.rb:885:in `block in system'
/usr/local/Library/Homebrew/formula.rb:842:in `open'
/usr/local/Library/Homebrew/formula.rb:842:in `system'
/usr/local/Library/Formula/clang-omp.rb:76:in `block in <class:ClangOmp>'
/usr/local/Library/Homebrew/formula.rb:785:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:781:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

If I try a the simple test from:
https://clang-omp.github.io
It find ```omp.h``` but not ```sodlib.h```:

```
(arctic)JB-MacBook:arctic james$ cat test_clang.c 
#include <omp.h>
#include <stdio.h>
int main() {
#pragma omp parallel
printf("Hello from thread %d, nthreads %d\n", omp_get_thread_num(), omp_get_num_threads());
}
(arctic)JB-MacBook:arctic james$ /usr/local/Cellar/clang-omp/2015-04-01/bin/clang-omp test_clang.c -liomp5 -fopenmp 
In file included from test_clang.c:1:
/usr/local/opt/libiomp/include/libiomp/omp.h:134:13: fatal error: 'stdlib.h' file not found
#   include <stdlib.h>
            ^
1 error generated.
```

Current system:

```
(arctic)JB-MacBook:arctic james$ uname -a
Darwin JB-MacBook.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
(arctic)JB-MacBook:arctic james$ clang --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

Any ideas?

**Comment by xu-cheng** [comment]
Does reinstall clang-omp do any help?

**Comment by jamesblackburn** [comment]
Doesn't seem to:

```
JB-MacBook:local james$ brew remove clang-omp
Uninstalling /usr/local/Cellar/clang-omp/2015-04-01... (1396 files, 378M)
JB-MacBook:local james$ brew install clang-omp
==> Downloading https://homebrew.bintray.com/bottles/clang-omp-2015-04-01.yosemite.bottle.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/clang-omp-2015-04-01.yosemite.bottle.2.tar.gz
==> Pouring clang-omp-2015-04-01.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/clang-omp/2015-04-01: 1396 files, 378M
JB-MacBook:local james$ brew test clang-omp
Testing clang-omp
==> /usr/local/Cellar/clang-omp/2015-04-01/bin/clang-omp -liomp5 -fopenmp test.c -o test

test.c:3:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.
acError: clang-omp: failed
Failed executing: /usr/local/Cellar/clang-omp/2015-04-01/bin/clang-omp -liomp5 -fopenmp test.c -o test
/usr/local/Library/Homebrew/formula.rb:885:in `block in system'
/usr/local/Library/Homebrew/formula.rb:842:in `open'
/usr/local/Library/Homebrew/formula.rb:842:in `system'
/usr/local/Library/Formula/clang-omp.rb:76:in `block in <class:ClangOmp>'
/usr/local/Library/Homebrew/formula.rb:785:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:781:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'

```

Did you mean something else?

**Comment by xu-cheng** [comment]
Ok in this case, can you try reinstall libiomp?  Both of formulae have been updated some time ago. I suspect you may install a old version for one of them.

**Comment by jamesblackburn** [comment]
I only recently installed brew for this package, so it's all new for -- I don't think it's a stale package issue.  I'm on Yosemite with the latest Xcode.

```
(arctic)JB-MacBook:arctic james$ brew remove libiomp
Uninstalling /usr/local/Cellar/libiomp/20150401... (8 files, 548K)
(arctic)JB-MacBook:arctic james$ brew install libiomp
==> Downloading https://homebrew.bintray.com/bottles/libiomp-20150401.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/libiomp-20150401.yosemite.bottle.tar.gz
==> Pouring libiomp-20150401.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libiomp/20150401: 8 files, 548K
(arctic)JB-MacBook:arctic james$ brew test clang-omp
Testing clang-omp
==> /usr/local/Cellar/clang-omp/2015-04-01/bin/clang-omp -liomp5 -fopenmp test.c -o test

test.c:3:10: fatal error: 'omp.h' file not found
...
```

**Comment by xu-cheng** [comment]
Can you paste the output of `brew config` and `brew doctor`?

**Comment by jamesblackburn** [comment]
Attached below... I notice a complaint about pig-config -- I wonder if that's the issue!

```
(arctic)JB-MacBook:arctic james$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 0099e5e5da718a4608fe78f0b9a5d34068308059
Last commit: 6 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit broadwell
OS X: 10.10.3-x86_64
Xcode: 6.3.2
CLT: N/A
Clang: 6.1 build 602
MacPorts/Fink: /opt/local/bin/port, /sw/bin/fink
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /opt/local/bin/perl => /opt/local/bin/perl5.12
Python: /Users/james/pyenvs/arctic/bin/python
Ruby: /usr/bin/ruby
Java: 1.8.0_25
(arctic)JB-MacBook:arctic james$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/etc/pkcs11/pkcs11.conf.example
  /usr/local/lib/pkgconfig/geoip.pc
  /usr/local/lib/pkgconfig/gio-2.0.pc
  /usr/local/lib/pkgconfig/gio-unix-2.0.pc
  /usr/local/lib/pkgconfig/glib-2.0.pc
  /usr/local/lib/pkgconfig/gmodule-2.0.pc
  /usr/local/lib/pkgconfig/gmodule-export-2.0.pc
  /usr/local/lib/pkgconfig/gmodule-no-export-2.0.pc
  /usr/local/lib/pkgconfig/gnutls.pc
  /usr/local/lib/pkgconfig/gobject-2.0.pc
  /usr/local/lib/pkgconfig/gthread-2.0.pc
  /usr/local/lib/pkgconfig/hogweed.pc
  /usr/local/lib/pkgconfig/liblzma.pc
  /usr/local/lib/pkgconfig/libtasn1.pc
  /usr/local/lib/pkgconfig/nettle.pc
  /usr/local/lib/pkgconfig/p11-kit-1.pc
  /usr/local/share/gtk-doc/html/p11-kit
  /usr/local/share/locale/af/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/am/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ar/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/as/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ast/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/az/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/be/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/be@latin/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/bg/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/bn/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/bn_IN/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/bs/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ca/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ca@valencia/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/cs/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/cy/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/da/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/de/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/dz/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/el/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/en@shaw/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/en_CA/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/en_GB/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/eo/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/es/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/et/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/eu/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/fa/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/fi/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/fr/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ga/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/gl/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/gu/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/he/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/hi/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/hr/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/hu/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/hy/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/id/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/is/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/it/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ja/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ka/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/kk/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/kn/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ko/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ku/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/lt/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/lv/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/mai/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/mg/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/mk/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ml/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/mn/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/mr/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ms/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/nb/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/nds/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ne/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/nl/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/nn/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/oc/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/or/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/pa/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/pl/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ps/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/pt/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/pt_BR/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ro/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ru/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/rw/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/si/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/sk/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/sl/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/sq/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/sr/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/sr@ije/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/sr@latin/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/sv/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ta/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/te/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/tg/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/th/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/tl/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/tr/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/tt/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/ug/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/uk/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/vi/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/wa/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/xh/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/yi/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/zh_CN/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/zh_HK/LC_MESSAGES/glib20.mo
  /usr/local/share/locale/zh_TW/LC_MESSAGES/glib20.mo
  /usr/local/Library/LinkedKegs/autoconf
  /usr/local/Library/LinkedKegs/automake
  /usr/local/Library/LinkedKegs/boost
  /usr/local/Library/LinkedKegs/geoip
  /usr/local/Library/LinkedKegs/glib
  /usr/local/Library/LinkedKegs/gnutls
  /usr/local/Library/LinkedKegs/libgcrypt
  /usr/local/Library/LinkedKegs/libgpg-error
  /usr/local/Library/LinkedKegs/libtasn1
  /usr/local/Library/LinkedKegs/libtool
  /usr/local/Library/LinkedKegs/nettle
  /usr/local/Library/LinkedKegs/p11-kit
  /usr/local/Library/LinkedKegs/pkg-config
  /usr/local/Library/LinkedKegs/wireshark
  /usr/local/Library/LinkedKegs/xz

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:

  /opt/local/bin/apr-1-config
  /opt/local/bin/apu-1-config
  /opt/local/bin/curl-config
  /opt/local/bin/freetype-config
  /opt/local/bin/krb5-config
  /opt/local/bin/libpng-config
  /opt/local/bin/libpng15-config
  /opt/local/bin/ncurses5-config
  /opt/local/bin/ncursesw5-config
  /opt/local/bin/neon-config
  /opt/local/bin/pcre-config
  /opt/local/bin/pkg-config
  /opt/local/bin/python2-config
  /opt/local/bin/python2.5-config
  /opt/local/bin/python2.7-config
  /opt/local/bin/xml2-config
  /sw/bin/apt-config
  /sw/bin/curl-config
  /sw/bin/gdlib-config
  /sw/bin/glib-config
  /sw/bin/libpng-config
  /sw/bin/libpng12-config
  /sw/bin/libusb-config
  /sw/bin/libwww-config
  /sw/bin/netpbm-config
  /sw/bin/octave-config
  /sw/bin/pdflib-config
  /sw/bin/pkg-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have MacPorts or Fink installed:
  /opt/local/bin/port, /sw/bin/fink

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libflickcurl.0.dylib
    /usr/local/lib/libMonoPosixHelper.dylib
    /usr/local/lib/librtmp.dylib
    /usr/local/lib/libSFFileMonitor.32.dylib
    /usr/local/lib/libSFIPC.32.dylib
    /usr/local/lib/libSFIPC.I.dylib
    /usr/local/lib/libSFsqlite3.7.4.dylib
    /usr/local/lib/libSFSyncEngine.I.dylib
    /usr/local/lib/libumem.0.0.0.dylib
    /usr/local/lib/libumem_malloc.0.0.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/flickcurl.h
    /usr/local/include/node/ares.h
    /usr/local/include/node/ares_version.h
    /usr/local/include/node/eio-emul.h
    /usr/local/include/node/ev-emul.h
    /usr/local/include/node/node.h
    /usr/local/include/node/node_buffer.h
    /usr/local/include/node/node_object_wrap.h
    /usr/local/include/node/node_version.h
    /usr/local/include/node/uv-private/eio.h
    /usr/local/include/node/uv-private/ev.h
    /usr/local/include/node/uv-private/ngx-queue.h
    /usr/local/include/node/uv-private/tree.h
    /usr/local/include/node/uv-private/uv-unix.h
    /usr/local/include/node/uv-private/uv-win.h
    /usr/local/include/node/uv.h
    /usr/local/include/node/v8-debug.h
    /usr/local/include/node/v8-preparser.h
    /usr/local/include/node/v8-profiler.h
    /usr/local/include/node/v8-testing.h
    /usr/local/include/node/v8.h
    /usr/local/include/node/v8stdint.h
    /usr/local/include/sys/vmem.h
    /usr/local/include/umem.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libflickcurl.la
    /usr/local/lib/libumem.la
    /usr/local/lib/libumem_malloc.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/flickcurl.pc
    /usr/local/lib/pkgconfig/fuse-ext2.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libflickcurl.a
    /usr/local/lib/libumem.a
    /usr/local/lib/libumem_malloc.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:

    gcc

Warning: You have uncommitted modifications to Homebrew
If this a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
    cd /usr/local/Library && git stash && git clean -d -f

Warning: You have a non-Homebrew 'pkg-config' in your PATH:
  /opt/local/bin/pkg-config

`./configure` may have problems finding brew-installed packages using
this other pkg-config.
Error: Failed to import: scantailor
version '{"0.9.11"=>Formulary::Formulae::Scantailor::Version}' should be a string

Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run `brew update`.

```

**Comment by jamesblackburn** [comment]
it's not pkg-config:

```
(arctic)JB-MacBook:arctic james$ export PATH=/usr/local/bin/:$PATH
(arctic)JB-MacBook:arctic james$ which pkg-config
/usr/local/bin//pkg-config
(arctic)JB-MacBook:arctic james$ brew test clang-omp
Testing clang-omp
==> /usr/local/Cellar/clang-omp/2015-04-01/bin/clang-omp -liomp5 -fopenmp test.c -o test

test.c:3:10: fatal error: 'omp.h' file not found
#include <omp.h>
```

**Comment by tdsmith** [comment]
Can you pass `-v` when you try and build the example to see what the include search path is?

**Comment by jamesblackburn** [comment]
```
(arctic)JB-MacBook:arctic james$ /usr/local/Cellar/clang-omp/2015-04-01/bin/clang-omp -v test.c
clang version 3.5.0 
Target: x86_64-apple-darwin14.3.0
Thread model: posix
 "/usr/local/Cellar/clang-omp/2015-04-01/libexec/bin/clang-3.5" -cc1 -triple x86_64-apple-macosx10.10.0 -emit-obj -mrelax-all -disable-free -main-file-name test.c -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -v -dwarf-column-info -resource-dir /usr/local/Cellar/clang-omp/2015-04-01/libexec/bin/../lib/clang/3.5.0 -fdebug-compilation-dir /Users/james/Projects/arctic -ferror-limit 19 -fmessage-length 134 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.10.0 -fencode-extended-block-signature -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/nv/854ddzmx43z7g6qm0m4p2bh80000gn/T/test-e88e22.o -x c test.c
clang -cc1 version 3.5.0 based upon LLVM 3.5.0svn default target x86_64-apple-darwin14.3.0
ignoring nonexistent directory "/usr/local/Cellar/clang-omp/2015-04-01/libexec/usr/include"
ignoring nonexistent directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /usr/local/Cellar/clang-omp/2015-04-01/libexec/bin/../lib/clang/3.5.0/include
 /usr/local/opt/libiomp/include/libiomp
 /usr/local/Cellar/clang-omp/2015-04-01/libexec/include/c++/v1
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
test.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
```

**Comment by ContinuedStory** [comment]
Try xcode-select --install in terminal.

**Comment by luisremis** [comment]
Thanks ContinuedStory! That solved my issue!

**Comment by MikeMcQuaid** [comment]
This formula was removed.
