### ISSUE TITLE
Error Bad URI thrown when tapping over proxy network without specifying http

### ISSUE THREAD

**Issue by sudheesh001** [Homebrew/legacy-homebrew#44564]
```
Error: bad URI(is not URI?): 172.30.0.14:3128
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:176:in `split'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/generic.rb:1672:in `find_proxy'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:193:in `block in open_loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `call'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
/usr/local/Library/Homebrew/utils.rb:373:in `open'
/usr/local/Library/Homebrew/utils.rb:460:in `private_repo?'
/usr/local/Library/Homebrew/tap.rb:69:in `private?'
/usr/local/Library/Homebrew/cmd/tap.rb:28:in `install_tap'
/usr/local/Library/Homebrew/cmd/tap.rb:12:in `tap'
/usr/local/Library/brew.rb:125:in `<main>'
```
Though the tap is completed, it throws up the error shown above.

**Comment by tdsmith** [comment]
Is `172.30.0.14:3128` where the tap is or your proxy? Where is that value set? Was it provided on the command line or through an environment variable?

**Comment by sudheesh001** [comment]
it's the proxy, i've set it in `export http_proxy=172.30.0.14:3128` and similarly for `https_proxy`

**Comment by MikeMcQuaid** [comment]
We've tweaked our proxy handling so this should be fixed now.
