### ISSUE TITLE
upgrading cask fails

### ISSUE THREAD

**Issue by emrehan** [Homebrew/legacy-homebrew#44610]
Upgrading cask fails on my machine with Homebrew 0.9.5 (git revision 1a0ee; last commit 2015-10-05).

I get the following output:
```
$ brew upgrade
==> Upgrading 22 outdated packages, with result:
caskroom/cask/brew-cask 0.57.0, ...
==> Upgrading caskroom/cask/brew-cask
==> Cloning https://github.com/caskroom/homebrew-cask.git
Updating /Library/Caches/Homebrew/brew-cask--git
==> Checking out tag v0.57.0
Error: parent directory is world writable but not sticky
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:545:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:212:in `install'
/usr/local/Library/Homebrew/cmd/upgrade.rb:71:in `upgrade_formula'
/usr/local/Library/Homebrew/cmd/upgrade.rb:44:in `block in upgrade'
/usr/local/Library/Homebrew/cmd/upgrade.rb:44:in `each'
/usr/local/Library/Homebrew/cmd/upgrade.rb:44:in `upgrade'
/usr/local/Library/brew.rb:133:in `<main>'
```

**Comment by bfontaine** [comment]
What does `brew doctor` say?

**Comment by emrehan** [comment]
```
$ brew doctor
Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.

Warning: /tmp is world-writable but does not have the sticky bit set.
Please run "Repair Disk Permissions" in Disk Utility.

Warning: Your Xcode (6.4) is outdated
Please update to Xcode 7.0.1.
Xcode can be updated from the App Store.
```

I run "Repair Disk Permissions" and it got worse:

```
$ brew doctor
Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.

Error: Permission denied - /tmp/doctor20151005-56094-1plzihp
```
Brew upgrade was failing with the same error.

Then I've set /tmp folder to chmod 777 and brew doctor outputs the first message again.

**Comment by DomT4** [comment]
What does `/bin/ls -lO /private` output?

**Comment by emrehan** [comment]
```
$ /bin/ls -lO /private
total 0
drwxr-xr-x  91 root  wheel  - 3094 Sep 24 17:08 etc
drwxr-xr-x   2 root  wheel  -   68 Sep 10  2014 tftpboot
drwxrwxrwt  45 root  wheel  - 1530 Sep 28 09:53 tmp
drwxr-xr-x  25 root  wheel  -  850 Apr  3  2015 var
```

**Comment by DomT4** [comment]
That seems fine. Can you do the same command for `/private/tmp` itself?

**Comment by jiegec** [comment]
This mine which works fine:
macbookair@172-11-2-205 /private> la
total 0
drwxr-xr-x@  6 root  wheel   204B Oct  1 10:03 .
drwxr-xr-x  30 root  wheel   1.1K Oct  2 06:40 ..
drwxr-xr-x  87 root  wheel   2.9K Oct  1 10:10 etc
drwxr-xr-x   2 root  wheel    68B Aug 23 07:28 tftpboot
drwxrwxrwt   8 root  wheel   272B Oct  3 23:32 tmp
drwxr-xr-x  24 root  wheel   816B Oct  1 10:09 var
macbookair@172-11-2-205 /private> la tmp
total 320
drwxrwxrwt   8 root        wheel   272B Oct  3 23:32 .
drwxr-xr-x@  6 root        wheel   204B Oct  1 10:03 ..
-rw-rw-rw-@  1 macbookair  wheel     0B Oct  2 17:24 .keystone_install_lock
drwx------   3 macbookair  wheel   102B Oct  3 23:31 KSOutOfProcessFetcher.501.HVXI9pQwBk_bgiVJaTNhiQNhqxc=
drwx------   3 macbookair  wheel   102B Oct  2 17:24 com.apple.launchd.TVoRNAooCh
drwx------   3 macbookair  wheel   102B Oct  2 17:24 com.apple.launchd.qIYJ5NjBHY
drwxrwxrwx  45 macbookair  wheel   1.5K Oct  4 12:22 com.sogou.inputmethod
-rw-------   1 macbookair  wheel   158K Oct  6 12:39 fm_sg_cloud_cache.v0.filemap.sogouime_3.3.0.74613_00000001_501

**Comment by emrehan** [comment]
```
$ ls -lO /private/tmp

total 0
drwx------  3 emrehan  wheel  -          102 Jun  4 16:51 KSOutOfProcessFetcher.501.qQkpPp2uZLdVc5pukHmfJMR4bkM=
srwxr-xr-x  1 emrehan  wheel  -            0 Jun  4 13:45 OSL_PIPE_501_SingleOfficeIPC_ea77fbed74ac6656cfb7149b2d117e4
-rw-r--r--  1 emrehan  staff  compressed   1 Mar 30  2011 RecoveryUpdatePayload
drwx------  3 emrehan  wheel  -          102 Sep  4 22:38 com.apple.launchd.0RI6EtFPuY
drwx------  3 emrehan  wheel  -          102 Sep  4 22:38 com.apple.launchd.33i6gjDjZZ
drwx------  3 emrehan  wheel  -          102 Aug  1 14:32 com.apple.launchd.3Uj2YHZISK
drwx------  3 emrehan  wheel  -          102 Jul 26 13:42 com.apple.launchd.4OsD4rdrKr
drwx------  3 emrehan  wheel  -          102 Jul  6 14:05 com.apple.launchd.6I4wcecxQo
drwx------  3 emrehan  wheel  -          102 Sep 10 10:04 com.apple.launchd.7TDAO9lhTJ
drwx------  3 emrehan  wheel  -          102 Aug  1 16:39 com.apple.launchd.8bNygVIq2z
drwx------  3 emrehan  wheel  -          102 Aug  1 16:20 com.apple.launchd.8h6VA4Oqie
drwx------  3 emrehan  wheel  -          102 Aug  1 16:20 com.apple.launchd.99Aihu0XlV
drwx------  3 emrehan  wheel  -          102 Jun  2 12:27 com.apple.launchd.9Wu4brTQFd
drwx------  3 emrehan  wheel  -          102 Jul  6 14:05 com.apple.launchd.BLi2P0hjYO
drwx------  3 emrehan  wheel  -          102 Aug  1 16:39 com.apple.launchd.F75PUdGLkw
drwx------  3 emrehan  wheel  -          102 Jun 12 09:44 com.apple.launchd.Ge47RPyxiH
drwx------  3 emrehan  wheel  -          102 Aug  1 16:39 com.apple.launchd.KTnQI9chNe
drwx------  3 emrehan  wheel  -          102 Aug  1 13:27 com.apple.launchd.NHRCkpplKy
drwx------  3 emrehan  wheel  -          102 Jun 11 21:45 com.apple.launchd.OETaxA1yXV
drwx------  3 emrehan  wheel  -          102 Jun 16 10:42 com.apple.launchd.PdLDtbfe8z
drwx------  3 emrehan  wheel  -          102 Jun 12 09:44 com.apple.launchd.XB8JMCIS4s
drwx------  3 emrehan  wheel  -          102 Sep 24 17:09 com.apple.launchd.YHeKJrxukC
drwx------  3 emrehan  wheel  -          102 Jul  6 11:13 com.apple.launchd.YSQ6T86KT1
drwx------  3 emrehan  wheel  -          102 Aug  1 16:20 com.apple.launchd.aSfSUca0sz
drwx------  3 emrehan  wheel  -          102 Jun 11 21:45 com.apple.launchd.bbHIzGSbwT
drwx------  3 emrehan  wheel  -          102 Jul 26 13:42 com.apple.launchd.c6GCwqiXrm
drwx------  3 emrehan  wheel  -          102 Sep 10 10:04 com.apple.launchd.cOwsbdTX1I
drwx------  3 emrehan  wheel  -          102 Aug  1 13:27 com.apple.launchd.dj9wgGN1yM
drwx------  3 emrehan  wheel  -          102 Jun  2 12:27 com.apple.launchd.eCLODk3vDA
drwx------  3 emrehan  wheel  -          102 Aug  1 14:32 com.apple.launchd.fRL0D0UTUj
drwx------  3 emrehan  wheel  -          102 Jul 26 13:42 com.apple.launchd.i9pDen5fyq
drwx------  3 emrehan  wheel  -          102 Jun 16 10:42 com.apple.launchd.lQkCZfdyth
drwx------  3 emrehan  wheel  -          102 Jul  6 14:05 com.apple.launchd.npwpfSrEau
drwx------  3 emrehan  wheel  -          102 Aug  1 13:27 com.apple.launchd.pZFC4LYzuH
drwx------  3 emrehan  wheel  -          102 Aug  1 14:32 com.apple.launchd.s0RYgWCONb
drwx------  3 emrehan  wheel  -          102 Sep 10 10:04 com.apple.launchd.sSND5GQzAu
drwx------  3 emrehan  wheel  -          102 Sep 24 17:09 com.apple.launchd.tICYdsQ8mb
drwx------  3 emrehan  wheel  -          102 Sep  4 22:38 com.apple.launchd.vaKfaTkxpm
drwx------  3 emrehan  wheel  -          102 Jul  6 11:13 com.apple.launchd.zDrXQKVMnV
drwx------  3 emrehan  wheel  -          102 Sep 24 17:09 com.apple.launchd.zLyoxpXgnp
drwxr-xr-x  7 root     wheel  -          238 Sep 28 09:53 org.gpgtools
```

**Comment by DomT4** [comment]
@emrehan Are you still having issues here?

**Comment by emrehan** [comment]
@DomT4; Yes, I still have the same error.

**Comment by mikemcquaid** [comment]
Let's see `/bin/ls -lO /Library/Caches/Homebrew/`

**Comment by emrehan** [comment]
```
$ bin/ls -lO /Library/Caches/Homebrew/

total 5818376
drwxr-xr-x   7 emrehan  admin  -        238 Oct 10 17:42 Casks
drwxr-xr-x  44 emrehan  admin  -       1496 Oct  5 10:10 Formula
-rw-r--r--   1 emrehan  admin  -     137778 Mar 28  2015 ack-2.14.14-single-file
-rw-r--r--   1 emrehan  admin  -  260140850 Apr  9  2015 android-studio-1.1.0.zip
-rw-r--r--   1 emrehan  admin  -    3154393 Jun  2 11:38 ansible-1.9.0.1.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -    9679074 Jul 14 20:08 ansible-1.9.2.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -   12487482 Oct  5 10:09 ansible-1.9.3.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -    5564593 Mar 29  2015 ant-1.9.4.tar.gz
-rw-r--r--   1 emrehan  admin  -    4383313 Jul 14 20:08 ant-1.9.5.tar.bz2
-rw-r--r--   1 emrehan  admin  -    5596826 Oct  5 10:10 ant-1.9.6.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -     891456 Aug 25 15:36 autoconf-2.69.yosemite.bottle.1.tar.gz
-rw-r--r--   1 emrehan  admin  -      52724 Mar 28  2015 autojump-22.2.4.tar.gz
-rw-r--r--   1 emrehan  admin  -     921852 Aug 25 15:36 automake-1.15.yosemite.bottle.tar.gz
drwxr-xr-x  27 emrehan  admin  -        918 Oct  5 10:10 brew-cask--git
-rw-r--r--   1 emrehan  admin  -     131829 Jul  6 13:56 c-ares-1.10.0.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -     776226 Jul  6 13:56 d-bus-1.8.14.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -      13141 Mar 28  2015 drip-0.2.4.tar.gz
-rw-r--r--   1 emrehan  admin  -       1668 Mar 28  2015 emacs--patch-fab5cf538ade6afa949640b0f81bdea26cb23b6d64ca714b687dee6f33ff270e.patch
-rw-r--r--   1 emrehan  admin  -   39733124 Mar 28  2015 emacs-24.4.tar.xz
-rw-r--r--   1 emrehan  admin  -      12639 Oct  4 20:47 entr-3.2.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -     167206 Mar 28  2015 gdbm-1.11.yosemite.bottle.2.tar.gz
-rw-r--r--   1 emrehan  admin  -     230133 Jul  6 13:56 geoip-1.6.5.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -    7166851 Jul  6 13:55 gettext-0.19.4.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -     984588 Apr  3  2015 git--html-2.3.5.tar.xz
-rw-r--r--   1 emrehan  admin  -     371644 Apr  3  2015 git--man-2.3.5.tar.xz
-rw-r--r--   1 emrehan  admin  -   10803273 Mar 28  2015 git-2.3.4.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -    3620472 Apr  3  2015 git-2.3.5.tar.xz
-rw-r--r--   1 emrehan  admin  -   10705270 Apr  3  2015 git-2.3.5.yosemite.bottle.tar.gz.incomplete
-rw-r--r--   1 emrehan  admin  -    5167817 Jul  6 13:55 glib-2.44.1.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -    1073950 Jul  6 13:55 gmp-6.0.0a.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -    1863250 Jul  6 13:55 gnutls-3.3.15.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -   44617449 Jul 29 17:47 gradle-2.5.zip
-rw-r--r--   1 emrehan  admin  -      28095 Mar 28  2015 grc-1.7.tar.gz
-rw-r--r--   1 emrehan  admin  -      28798 Apr  3  2015 grc-1.9.tar.gz
-rw-r--r--   1 emrehan  admin  -     752275 Apr  6  2015 heroku-toolbelt-3.30.4.tgz
-rw-r--r--   1 emrehan  admin  -      18119 Mar 28  2015 jenv-0.4.2.tar.gz
-rw-r--r--   1 emrehan  admin  -    1482545 Oct 10 17:42 keepingyouawake-1.2.1.zip
-rw-r--r--   1 emrehan  admin  -   15268189 Mar 28  2015 leiningen--jar-2.5.1.zip
-rw-r--r--   1 emrehan  admin  -     676339 Mar 28  2015 leiningen-2.5.1.tar.gz
-rw-r--r--   1 emrehan  admin  -   14193199 Oct  5 10:09 leiningen-2.5.3.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -     113819 Jul  6 13:55 libffi-3.0.13.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -     483606 Jul  6 13:55 libgcrypt-1.6.3.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -      96352 Jul  6 13:55 libgpg-error-1.19.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -     129530 Aug 25 15:36 libksba-1.3.3.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -     136121 Jul  6 13:55 libtasn1-4.5.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -    1035171 Aug 25 15:36 libtool-2.4.6.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -     109330 Jun  2 11:38 libyaml-0.1.6_1.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  - 2218479786 May  3  2015 mactex-20140525.pkg.incomplete
-rw-r--r--   1 emrehan  admin  -    8059952 Apr  4  2015 maven-3.3.1.tar.gz
-rw-r--r--   1 emrehan  admin  -     654955 Jul  6 13:55 nettle-2.7.1.yosemite.bottle.1.tar.gz
-rw-r--r--   1 emrehan  admin  -    6038306 Mar 29  2015 node-0.12.1.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -    6246972 Apr  3  2015 node-0.12.2.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -    3859368 Mar 28  2015 openssl-1.0.2a-1.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -    3809976 Aug 25 15:37 openssl-1.0.2d_1.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -    1045239 Jul 14 13:26 parallel-20150522.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -    1841810 Mar 28  2015 pcre-8.36.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -     225402 Mar 28  2015 pkg-config-0.28.yosemite.bottle.2.tar.gz
-rw-r--r--   1 emrehan  admin  -   19388556 Mar 28  2015 python3-3.4.3.yosemite.bottle.6.tar.gz
-rw-r--r--   1 emrehan  admin  -     759288 Mar 28  2015 readline-6.3.8.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -       2368 Mar 31  2015 rmtrash-0.3.3.tar.gz
-rw-r--r--   1 emrehan  admin  -    1061613 Jun  4 17:40 sbt-0.13.8.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -     963278 Mar 28  2015 sqlite-3.8.8.3.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -      47082 Mar 29  2015 tree-1.7.0.tgz
-rw-r--r--@  1 emrehan  admin  -   82012877 Jun  2 12:14 vagrant-1.7.2.dmg
-rw-r--r--@  1 emrehan  admin  -  113974554 Jun  2 12:28 virtualbox-4.3.26-98988.dmg
-rw-r--r--@  1 emrehan  admin  -   26527702 Jul  8 16:14 visualvm-1.3.8.dmg
-rw-r--r--   1 emrehan  admin  -     532754 Mar 28  2015 wget-1.16.3.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -   15149601 Jul  6 13:56 wireshark-1.12.6.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -     462886 Mar 28  2015 xz-5.2.1.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -    2516928 Mar 28  2015 zsh-5.0.7.yosemite.bottle.tar.gz
-rw-r--r--   1 emrehan  admin  -     193410 Mar 28  2015 zsh-completions-0.12.0.tar.gz
```

**Comment by DomT4** [comment]
I'd probably `brew cleanup --prune=1` there. What does `brew doctor` say at the moment?

**Comment by emrehan** [comment]
I did `brew cleanup --prune=1,`but it didn't help. My OSX, Xcode and brew were updated as well.

After the cleanup my brew doctor prints the following:
```
Warning: Your XQuartz (2.7.7) is outdated
Please install XQuartz 2.7.8:
  https://xquartz.macosforge.org

Warning: /tmp is world-writable but does not have the sticky bit set.
Please run "Repair Disk Permissions" in Disk Utility.

Warning: Your Xcode (7.0.1) is outdated
Please update to Xcode 7.1.
Xcode can be updated from the App Store.
```

**Comment by UniqMartin** [comment]
Closing as there have been significant changes to Cask since this issue was opened, particularly it's no longer a formula that needs to be installed/upgraded; happy to reopen should I be mistaken and there's still an issue that needs to be solved.

**Comment by emrehan** [comment]
Hi @UniqMartin. Thank you for keeping an eye on the issue. I reinstalled my OS, therefore I cannot reproduce the error.
