### ISSUE TITLE
brew throws an error when doing a `brew search` with a proxy setting turned on

### ISSUE THREAD

**Issue by welladamm** [Homebrew/legacy-homebrew#45129]
```shell
○ type brew
brew is an alias for http_proxy="127.0.0.1:1080" https_proxy="127.0.0.1:1080" brew
```

```shell
○ brew search docker
boot2docker                         docker (installed)                  docker-compose (installed)          docker-machine (installed)          docker-swarm
Error: bad URI(is not URI?): 127.0.0.1:1080
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:176:in `split'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/generic.rb:1672:in `find_proxy'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:193:in `block in open_loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `call'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
/usr/local/Library/Homebrew/utils.rb:461:in `open'
/usr/local/Library/Homebrew/cmd/search.rb:116:in `block in search_tap'
/usr/local/Library/Homebrew/cmd/search.rb:133:in `yield'
/usr/local/Library/Homebrew/cmd/search.rb:133:in `search_tap'
/usr/local/Library/Homebrew/cmd/search.rb:100:in `block (2 levels) in search_taps'
```

```shell
○ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: c20248ad2b14a0c385a7b975907b296fbf0341c7
Last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11.1-x86_64
Xcode: N/A
CLT: 7.0.0.0.1.1441394355
Clang: 7.0 build 700
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.7.0_79, 1.6.0_65-b14-468
```

```shell
○ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You may have installed MacGPG2 via the package installer.
Several other checks in this script will turn up problems, such as stray
dylibs in /usr/local and permissions issues with share and man in /usr/local/.
```

**Comment by welladamm** [comment]
Seems to be an issue related to brew tap:

```shell
○ brew install petere/auto-update/brew-auto-update --HEAD
==> Tapping petere/auto-update
Cloning into '/usr/local/Library/Taps/petere/homebrew-auto-update'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
Checking connectivity... done.
Tapped 1 formula (30 files, 124K)
Error: bad URI(is not URI?): 127.0.0.1:1080
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:176:in `split'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/generic.rb:1672:in `find_proxy'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:193:in `block in open_loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `call'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
/usr/local/Library/Homebrew/utils.rb:461:in `open'
/usr/local/Library/Homebrew/utils.rb:548:in `private_repo?'
/usr/local/Library/Homebrew/tap.rb:80:in `private?'
/usr/local/Library/Homebrew/cmd/tap.rb:47:in `install_tap'
/usr/local/Library/Homebrew/cmd/install.rb:19:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:16:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:16:in `install'
/usr/local/Library/brew.rb:146:in `<main>'
```

**Comment by xu-cheng** [comment]
The root is `open-uri` doesn't support proxy well. We may consider to move away `open-uri` all together, since it has poor performance(by creating unnecessary temporary files) and [possible security problem](http://sakurity.com/blog/2015/02/28/openuri.html). Alternative, we can use `Net::HTTP` directly as what we do in `gist-logs` and maybe cleanup the duplicated codes in the process.'

A PR is welcome.

**Comment by MikeMcQuaid** [comment]
We fixed this.
