### ISSUE TITLE
pstoedit test is failing

### ISSUE THREAD

**Issue by apjanke** [Homebrew/legacy-homebrew#48661]
The pstoedit test is failing, both on my local 10.9.5 box, and in the CI when pulled in for the freetype formula (#44587).

Looks like it's calling ghostscript's `gs` from the wrong location.

```
sh: /usr/local/opt/ghostscript/bin/gs: No such file or directory
...
$ ls /usr/local/opt/ghostscript
gls: cannot access '/usr/local/opt/ghostscript': No such file or directory
$ which gs
/usr/local/bin/gs
```

Full error listing:

```
$ brew test pstoedit
Testing pstoedit
==> Using the sandbox
==> /usr/local/Cellar/pstoedit/3.70/bin/pstoedit -f pdf /usr/local/Library/Homebrew/test/fixt
Last 15 lines from /Users/janke/Library/Logs/Homebrew/pstoedit/01.pstoedit:
2016-01-30 23:11:31 -0500

/usr/local/Cellar/pstoedit/3.70/bin/pstoedit
-f
pdf
/usr/local/Library/Homebrew/test/fixtures/test.ps
test.pdf

pstoedit: version 3.70 / DLL interface 108 (built: May 20 2015 - release build - g++ 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57) - 64-bit) : Copyright (C) 1993 - 2014 Wolfgang Glunz
Info: This PDF driver is not very elaborated - consider using -f gs:pdfwrite instead.
sh: /usr/local/opt/ghostscript/bin/gs: No such file or directory
PostScript/PDF Interpreter finished. Return status 32512 executed command : /usr/local/opt/ghostscript/bin/gs -q -dDELAYBIND -dWRITESYSTEMDICT -dNODISPLAY -dNOEPS /var/folders/4v/dn9gt66149127ydhcn9vvr4c0000gn/T//psinKTPaKQ
The interpreter seems to have failed, cannot proceed !
Error: pstoedit: failed
Failed executing: /usr/local/Cellar/pstoedit/3.70/bin/pstoedit -f pdf /usr/local/Library/Homebrew/test/fixtures/test.ps test.pdf
/usr/local/Library/Homebrew/formula.rb:1477:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1414:in `open'
/usr/local/Library/Homebrew/formula.rb:1414:in `system'
/usr/local/Library/Formula/pstoedit.rb:47:in `block in <class:Pstoedit>'
/usr/local/Library/Homebrew/formula.rb:1323:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1319:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by apjanke** [comment]
I think this is because the ghostscript installation on my machine was messed up. The `/usr/local/opt/ghostscript` directory didn't exist, and when I tried to reinstall ghostscript, I got a link error.

```
$ brew install ghostscript
==> Downloading https://homebrew.bintray.com/bottles/ghostscript-9.18.mavericks.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/ghostscript-9.18.mavericks.bottle.tar.gz
==> Pouring ghostscript-9.18.mavericks.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/dvipdf
Target /usr/local/bin/dvipdf
already exists. You may want to remove it:
  rm '/usr/local/bin/dvipdf'

To force the link and overwrite all conflicting files:
  brew link --overwrite ghostscript

To list all files that would be deleted:
  brew link --overwrite --dry-run ghostscript

Possible conflicting files are:
/usr/local/bin/dvipdf
/usr/local/bin/eps2eps
/usr/local/bin/font2c
/usr/local/bin/gs -> /usr/local/bin/gs-X11
```

On the `freetype` tests, it looks like ghostscript is being uninstalled before the pstoedit test is run for the second time.


<img width="820" alt="screen shot 2016-01-30 at 11 24 51 pm" src="https://cloud.githubusercontent.com/assets/2618447/12700233/be4c6cae-c7a8-11e5-93bb-aafcdfbf9bcc.png">

**Comment by apjanke** [comment]
Nevermind, mostly. My local failure was due to a non-brewed ghostscript breaking the ghostscript link step, so the dependency was broken.

Might indicate an issue with the `brew` dependency logic. The failed link step for `ghostscript` did not abort the installation of `pstoedit`, and even though `brew install` exited nonzero, there was no error message visible on the screen because diagnostic info had scrolled the error off the terminal window, and the "successful install" 🍺 beer emoji was displayed. I didn't even notice the installation had failed. If it wasn't for the fact that I have an exit status indicator in my custom shell prompt,

```
$ brew install pstoedit
==> Installing dependencies for pstoedit: plotutils, little-cms2, ghostscript, imagema
==> Installing pstoedit dependency: plotutils
==> Downloading https://homebrew.bintray.com/bottles/plotutils-2.6_1.mavericks.bottle.1.tar.g
######################################################################## 100.0%
==> Pouring plotutils-2.6_1.mavericks.bottle.1.tar.gz
🍺  /usr/local/Cellar/plotutils/2.6_1: 69 files, 6.9M
==> Installing pstoedit dependency: little-cms2
==> Downloading https://homebrew.bintray.com/bottles/little-cms2-2.7.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring little-cms2-2.7.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/little-cms2/2.7: 16 files, 1M
==> Installing pstoedit dependency: ghostscript
==> Downloading https://homebrew.bintray.com/bottles/ghostscript-9.18.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring ghostscript-9.18.mavericks.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/dvipdf
Target /usr/local/bin/dvipdf
already exists. You may want to remove it:
  rm '/usr/local/bin/dvipdf'

To force the link and overwrite all conflicting files:
  brew link --overwrite ghostscript

To list all files that would be deleted:
  brew link --overwrite --dry-run ghostscript

Possible conflicting files are:
/usr/local/bin/dvipdf
/usr/local/bin/eps2eps
/usr/local/bin/font2c
/usr/local/bin/gs -> /usr/local/bin/gs-X11
/usr/local/bin/gsbj
/usr/local/bin/gsdj
/usr/local/bin/gsdj500
/usr/local/bin/gslj
/usr/local/bin/gslp
/usr/local/bin/gsnd
/usr/local/bin/lprsetup.sh
/usr/local/bin/pdf2dsc
/usr/local/bin/pdf2ps
/usr/local/bin/pf2afm
/usr/local/bin/pfbtopfa
/usr/local/bin/pphs
/usr/local/bin/printafm
/usr/local/bin/ps2ascii
/usr/local/bin/ps2epsi
/usr/local/bin/ps2pdf
/usr/local/bin/ps2pdf12
/usr/local/bin/ps2pdf13
/usr/local/bin/ps2pdf14
/usr/local/bin/ps2pdfwr
/usr/local/bin/ps2ps
/usr/local/bin/ps2ps2
/usr/local/bin/unix-lpr.sh
/usr/local/bin/wftopfa
/usr/local/share/man/man1/dvipdf.1
/usr/local/share/man/man1/eps2eps.1 -> /usr/local/share/man/man1/ps2ps.1
/usr/local/share/man/man1/font2c.1
/usr/local/share/man/man1/gs.1
/usr/local/share/man/man1/gsbj.1 -> /usr/local/share/man/man1/gslp.1
/usr/local/share/man/man1/gsdj.1 -> /usr/local/share/man/man1/gslp.1
/usr/local/share/man/man1/gsdj500.1 -> /usr/local/share/man/man1/gslp.1
/usr/local/share/man/man1/gslj.1 -> /usr/local/share/man/man1/gslp.1
/usr/local/share/man/man1/gslp.1
/usr/local/share/man/man1/gsnd.1
/usr/local/share/man/man1/pdf2dsc.1
/usr/local/share/man/man1/pdf2ps.1
/usr/local/share/man/man1/pf2afm.1
/usr/local/share/man/man1/pfbtopfa.1
/usr/local/share/man/man1/printafm.1
/usr/local/share/man/man1/ps2ascii.1
/usr/local/share/man/man1/ps2epsi.1
/usr/local/share/man/man1/ps2pdf.1
/usr/local/share/man/man1/ps2pdf12.1 -> /usr/local/share/man/man1/ps2pdf.1
/usr/local/share/man/man1/ps2pdf13.1 -> /usr/local/share/man/man1/ps2pdf.1
/usr/local/share/man/man1/ps2pdf14.1 -> /usr/local/share/man/man1/ps2pdf.1
/usr/local/share/man/man1/ps2pdfwr.1
/usr/local/share/man/man1/ps2ps.1
/usr/local/share/man/man1/wftopfa.1
==> Summary
🍺  /usr/local/Cellar/ghostscript/9.18: 709 files, 61M
==> Installing pstoedit dependency: imagemagick
==> Downloading https://homebrew.bintray.com/bottles/imagemagick-6.9.3-0.mavericks.bottle.1.t
######################################################################## 100.0%
==> Pouring imagemagick-6.9.3-0.mavericks.bottle.1.tar.gz
🍺  /usr/local/Cellar/imagemagick/6.9.3-0: 1,453 files, 17.7M
==> Installing pstoedit
==> Downloading https://homebrew.bintray.com/bottles/pstoedit-3.70.mavericks.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring pstoedit-3.70.mavericks.bottle.1.tar.gz
🍺  /usr/local/Cellar/pstoedit/3.70: 34 files, 1.9M
[✘ /usr/local on ⇄ master]
$ brew test pstoedit
Testing pstoedit
==> Using the sandbox
==> /usr/local/Cellar/pstoedit/3.70/bin/pstoedit -f pdf /usr/local/Library/Homebrew/test/fixt
Last 15 lines from /Users/janke/Library/Logs/Homebrew/pstoedit/01.pstoedit:
2016-01-30 23:11:31 -0500

/usr/local/Cellar/pstoedit/3.70/bin/pstoedit
-f
pdf
/usr/local/Library/Homebrew/test/fixtures/test.ps
test.pdf

pstoedit: version 3.70 / DLL interface 108 (built: May 20 2015 - release build - g++ 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57) - 64-bit) : Copyright (C) 1993 - 2014 Wolfgang Glunz
Info: This PDF driver is not very elaborated - consider using -f gs:pdfwrite instead.
sh: /usr/local/opt/ghostscript/bin/gs: No such file or directory
PostScript/PDF Interpreter finished. Return status 32512 executed command : /usr/local/opt/ghostscript/bin/gs -q -dDELAYBIND -dWRITESYSTEMDICT -dNODISPLAY -dNOEPS /var/folders/4v/dn9gt66149127ydhcn9vvr4c0000gn/T//psinKTPaKQ
The interpreter seems to have failed, cannot proceed !
Error: pstoedit: failed
```

**Comment by Atcold** [comment]
I have the same issue. Did you figure out a solution, perhaps?

**Comment by apjanke** [comment]
Sounds good. Probably don't need to modify the formula for that since it's a conflict with software installed by other means and should show up under `brew doctor`.

Thanks!
