### ISSUE TITLE
encfs: sandboxed test fails, unsandboxed succeeds

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/legacy-homebrew#50602]
Reported to upstream: https://github.com/vgough/encfs/issues/151

```
iMac-TMP:homebrew joe$ brew test -v encfs
Testing homebrew/fuse/encfs
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160401-75876-oebm9n.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-fuse/Formula/encfs.rb -v
==> yes | /usr/local/Cellar/encfs/1.8.1_1/bin/encfs --standard --extpass=/private/tmp/encfs20160401-75877-1kvgllv/print-password /private/tmp/encfs20160401-75877-1kvgllv/a /private/tmp/encfs20160401-75877-1kvgllv/b
The directory "/private/tmp/encfs20160401-75877-1kvgllv/a/" does not exist. Should it be created? (y,n) The directory "/private/tmp/encfs20160401-75877-1kvgllv/b" does not exist. Should it be created? (y,n) Creating new encrypted volume.
Standard configuration selected.

Configuration finished.  The filesystem to be created has
the following properties:
the OSXFUSE file system is not available (-1)
fuse failed.  Common problems:
 - fuse kernel module not installed (modprobe fuse)
 - invalid options -- see usage message
Filesystem cipher: "ssl/aes", version 3:0:2
Filename encoding: "nameio/block", version 4:0:2
Key Size: 192 bits
Block Size: 1024 bytes
Each file contains 8 byte header with unique IV data.
Filenames encoded using IV chaining mode.
File holes passed through to ciphertext.

Now you will need to enter a password for your filesystem.
You will need to remember this password, as there is absolutely
no recovery mechanism.  However, the password can be changed
later using encfsctl.

the OSXFUSE file system is not available (1)
fuse failed.  Common problems:
 - fuse kernel module not installed (modprobe fuse)
 - invalid options -- see usage message
Filesystem cipher: "ssl/aes", version 3:0:2
Filename encoding: "nameio/block", version 4:0:2
Key Size: 192 bits
Block Size: 1024 bytes
Each file contains 8 byte header with unique IV data.
Filenames encoded using IV chaining mode.
File holes passed through to ciphertext.

Now you will need to enter a password for your filesystem.
You will need to remember this password, as there is absolutely
no recovery mechanism.  However, the password can be changed
later using encfsctl.

==> Sandbox log
Apr  1 03:06:56 sandboxd[128]: encfs(75889) deny forbidden-exec-sugid
Error: homebrew/fuse/encfs: failed
Failed executing: yes | /usr/local/Cellar/encfs/1.8.1_1/bin/encfs --standard --extpass=/private/tmp/encfs20160401-75877-1kvgllv/print-password /private/tmp/encfs20160401-75877-1kvgllv/a /private/tmp/encfs20160401-75877-1kvgllv/b 
/usr/local/Library/Homebrew/formula.rb:1481:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1418:in `open'
/usr/local/Library/Homebrew/formula.rb:1418:in `system'
/usr/local/Library/Taps/homebrew/homebrew-fuse/Formula/encfs.rb:38:in `block in <class:Encfs>'
/usr/local/Library/Homebrew/formula.rb:1327:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:37:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1323:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```
```
iMac-TMP:homebrew joe$ brew test -vd encfs
/usr/local/Library/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-fuse/Formula/encfs.rb
Testing homebrew/fuse/encfs
Warning: The sandbox cannot be used in debug or interactive mode.
/usr/local/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Library/Taps/homebrew/homebrew-fuse/Formula/encfs.rb
==> yes | /usr/local/Cellar/encfs/1.8.1_1/bin/encfs --standard --extpass=/private/tmp/encfs20160401-75930-952ezh/print-password /private/tmp/encfs20160401-75930-952ezh/a /private/tmp/encfs20160401-75930-952ezh/b
The directory "/private/tmp/encfs20160401-75930-952ezh/a/" does not exist. Should it be created? (y,n) The directory "/private/tmp/encfs20160401-75930-952ezh/b" does not exist. Should it be created? (y,n) Creating new encrypted volume.
Standard configuration selected.

Configuration finished.  The filesystem to be created has
the following properties:
==> umount /private/tmp/encfs20160401-75930-952ezh/b
iMac-TMP:homebrew joe$ 
```

**Comment by mikemcquaid** [comment]
Maybe just worth simplifying the current test so it works for now?

**Comment by ilovezfs** [comment]
For now https://github.com/Homebrew/homebrew-fuse/pull/35 is good enough, I think. Unfortunately, upstream hasn't responded.
