### ISSUE TITLE
Error: undefined method `>' for nil:NilClass

### ISSUE THREAD

**Issue by Soroush-Co** [Homebrew/legacy-homebrew#50671]
Ran brew doctor, fixed as many issues as possible and retried your prior step?

# brew doctor
```
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Warning: No developer tools installed.
Install the Command Line Tools:
  xcode-select --install

Warning: Your XQuartz (2.7.7) is outdated
Please install XQuartz 2.7.8:
  https://xquartz.macosforge.org


Error: undefined method `>' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/diagnostic.rb:419:in `check_for_osx_gcc_installer'
/usr/local/Library/Homebrew/cmd/doctor.rb:42:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Library/brew.rb:87:in `<main>'

```

# Git status
```
$ cd /usr/local && git status
On branch master
nothing to commit, working directory clean
```

# brew config
```
SilverStar$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8284fb3fef9860a67f3303f17cb6fd99a2ebc168
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 836f178030a31f4519daa3e4bd172cd117244e67
Core tap last commit: 13 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11.4-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
MacPorts/Fink: /opt/local/bin/port
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p648
Perl: /opt/local/bin/perl => /opt/local/bin/perl5.16
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.1/bin/ruby
Java: 1.6.0_65-b14-468
```

**Comment by ilovezfs** [comment]
where's xcode?

**Comment by apjanke** [comment]
Here's a PR that'll get rid of that "undefined method" error, so you'll get better `brew doctor` output. That error may be masking other things that `doctor` would otherwise report.

https://github.com/Homebrew/brew/pull/197

**Comment by apjanke** [comment]
That PR is merged. Do a `brew update` and rerun `brew doctor` and you'll get better output instead of that error.

**Comment by Soroush-Co** [comment]
After install X-code this problem is resolved
@ilovezfs Thanks
